language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

install:
  - pip install pytest requests

script:
  - py.test -v -s -rsX self_test api_testing

env:
    matrix:
        - REPO_URL=https://github.com/okfn/ckan#maste
        - REPO_URL=https://github.com/rshk/ckan#bug-1363-error-500-api-empty-database
