language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

install:
  - ./simple_api_testing/travis-install.sh

script:
  - ./simple_api_testing/travis-run.sh

env:
  matrix:
    - REPO_URL=https://github.com/okfn/ckan REPO_BRANCH=master
    - REPO_URL=https://github.com/rshk/ckan REPO_BRANCH=master
    - REPO_URL=https://github.com/rshk/ckan REPO_BRANCH=integration

matrix:
  allow_failures:
    - env: REPO_URL=https://github.com/okfn/ckan REPO_BRANCH=master
    - env: REPO_URL=https://github.com/rshk/ckan REPO_BRANCH=master
